name: Build and Test

on:
  push:
    branches:
      - main
      - 'copilot/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      
      - name: Build action
        run: npm run build
      
      - name: Check for uncommitted changes
        run: |
          git diff --exit-code dist/ || (echo "::error::Built files are out of sync. Please run 'npm run build' and commit the changes." && exit 1)

  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Run Cucumber tests
        run: npm run test:cucumber
      
      - name: Validate coverage
        uses: vlindersoftware/validate-coverage@v1
        with:
          coverage-file: coverage/cobertura-coverage.xml
      
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
